"""add concept_diagrams table

Revision ID: 6108c9c0deb5
Revises: b3617c78aae9
Create Date: 2026-04-08 22:01:23.781208
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6108c9c0deb5'
down_revision: Union[str, None] = 'b3617c78aae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_diagrams',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('concept_key', sa.String(length=200), nullable=False),
    sa.Column('concept_label', sa.String(length=200), nullable=False),
    sa.Column('diagram_type', sa.String(length=50), nullable=False),
    sa.Column('mermaid_code', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_concept_diagrams_user_concept', 'concept_diagrams', ['user_id', 'concept_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_concept_diagrams_user_concept', table_name='concept_diagrams')
    op.drop_table('concept_diagrams')
    # ### end Alembic commands ###
