"""add tips_text to quiz_items table

Revision ID: a477dd4e7677
Revises: e6c32322f187
Create Date: 2026-04-02 14:46:03.009001
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a477dd4e7677'
down_revision: Union[str, None] = 'e6c32322f187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_items', sa.Column('tips_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_items', 'tips_text')
    # ### end Alembic commands ###
