"""add_user_tier_fields

Revision ID: ac190b624b44
Revises: f3a8b2c5d914
Create Date: 2026-04-06 13:40:38.563414
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "ac190b624b44"
down_revision: Union[str, None] = "f3a8b2c5d914"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("tier", sa.String(length=20), nullable=False, server_default="free"),
    )
    op.add_column(
        "users", sa.Column("stripe_customer_id", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("free_trial_used_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "free_trial_used_at")
    op.drop_column("users", "stripe_customer_id")
    op.drop_column("users", "tier")
    # ### end Alembic commands ###
