"""add_email_verification_and_signup_ip

Revision ID: b3617c78aae9
Revises: 00619708a6f1
Create Date: 2026-04-08 12:45:39.938291
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "b3617c78aae9"
down_revision: Union[str, None] = "00619708a6f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("selector", sa.String(length=22), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_verification_tokens_selector"),
        "email_verification_tokens",
        ["selector"],
        unique=False,
    )
    op.create_foreign_key(
        None, "answer_logs", "answer_logs", ["regraded_from_answer_log_id"], ["id"]
    )
    op.alter_column(
        "refresh_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_subscriptions_paddle_subscription_id"), table_name="subscriptions"
    )
    op.create_unique_constraint(None, "subscriptions", ["paddle_subscription_id"])
    op.add_column(
        "users",
        sa.Column(
            "email_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("signup_ip", sa.String(length=45), nullable=True))
    # ### end Alembic commands ###

    # Grandfather existing users - set email_verified to true for all existing users
    op.execute("UPDATE users SET email_verified = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "signup_ip")
    op.drop_column("users", "email_verified")
    op.drop_constraint(None, "subscriptions", type_="unique")
    op.create_index(
        op.f("ix_subscriptions_paddle_subscription_id"),
        "subscriptions",
        ["paddle_subscription_id"],
        unique=True,
    )
    op.alter_column(
        "refresh_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "answer_logs", type_="foreignkey")
    op.drop_index(
        op.f("ix_email_verification_tokens_selector"),
        table_name="email_verification_tokens",
    )
    op.drop_table("email_verification_tokens")
    # ### end Alembic commands ###
