"""add_study_content_models

Revision ID: f7a7439a2e93
Revises: 60b1f1a43019
Create Date: 2026-04-14 19:29:04.587558
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f7a7439a2e93'
down_revision: Union[str, None] = '60b1f1a43019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_chats',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_flashcard_sets',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('not_generated', 'generating', 'completed', 'failed', name='contentstatus', native_enum=False), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_mindmaps',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('not_generated', 'generating', 'completed', 'failed', name='contentstatus', native_enum=False), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_summaries',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('not_generated', 'generating', 'completed', 'failed', name='contentstatus', native_enum=False), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_flashcards',
    sa.Column('flashcard_set_id', sa.String(length=36), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_set_id'], ['study_flashcard_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_messages',
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='messagerole', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_context', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['study_chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('admin_settings', 'active_grading_model')
    op.drop_column('admin_settings', 'fallback_grading_model')
    op.drop_index(op.f('ix_answer_logs_guest_active'), table_name='answer_logs', postgresql_where='(guest_session_id IS NOT NULL)')
    op.drop_index(op.f('ix_answer_logs_guest_session_id'), table_name='answer_logs')
    op.drop_index(op.f('ix_files_guest_session_id'), table_name='files')
    op.drop_index(op.f('ix_guest_sessions_created_at'), table_name='guest_sessions')
    op.drop_index(op.f('ix_quiz_sessions_guest_session_id'), table_name='quiz_sessions')
    op.drop_column('quiz_sessions', 'grading_model_name')
    op.drop_column('users', 'free_trial_used_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('free_trial_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('quiz_sessions', sa.Column('grading_model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_quiz_sessions_guest_session_id'), 'quiz_sessions', ['guest_session_id'], unique=False)
    op.create_index(op.f('ix_guest_sessions_created_at'), 'guest_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_files_guest_session_id'), 'files', ['guest_session_id'], unique=False)
    op.create_index(op.f('ix_answer_logs_guest_session_id'), 'answer_logs', ['guest_session_id'], unique=False)
    op.create_index(op.f('ix_answer_logs_guest_active'), 'answer_logs', ['guest_session_id', 'is_active_result'], unique=False, postgresql_where='(guest_session_id IS NOT NULL)')
    op.add_column('admin_settings', sa.Column('fallback_grading_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('admin_settings', sa.Column('active_grading_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_table('study_messages')
    op.drop_table('study_flashcards')
    op.drop_table('study_summaries')
    op.drop_table('study_mindmaps')
    op.drop_table('study_flashcard_sets')
    op.drop_table('study_chats')
    # ### end Alembic commands ###
